"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const Paths_1 = __importDefault(require("@src/common/constants/Paths"));
const EquipmentRoutes_1 = __importDefault(require("@src/controllers/EquipmentRoutes"));
const HelathRoutes_1 = __importDefault(require("@src/controllers/HelathRoutes"));
const MaintenanceRequestsRoutes_1 = __importDefault(require("@src/controllers/MaintenanceRequestsRoutes"));
const UserRoutes_1 = __importDefault(require("@src/controllers/UserRoutes"));
const apiRouter = (0, express_1.Router)();
apiRouter.get(Paths_1.default.Health._, HelathRoutes_1.default.health);
const userRouter = (0, express_1.Router)();
userRouter.get(Paths_1.default.Users.Get, UserRoutes_1.default.getAll);
userRouter.post(Paths_1.default.Users.Add, UserRoutes_1.default.add);
userRouter.put(Paths_1.default.Users.Update, UserRoutes_1.default.update);
userRouter.delete(Paths_1.default.Users.Delete, UserRoutes_1.default.delete);
apiRouter.use(Paths_1.default.Users._, userRouter);
const equipmentRouter = (0, express_1.Router)();
equipmentRouter.get(Paths_1.default.Equipment.Get, EquipmentRoutes_1.default.get);
equipmentRouter.post(Paths_1.default.Equipment.Add, EquipmentRoutes_1.default.add);
equipmentRouter.get(Paths_1.default.Equipment.GetId, EquipmentRoutes_1.default.getById);
equipmentRouter.patch(Paths_1.default.Equipment.Patch, EquipmentRoutes_1.default.patch);
equipmentRouter.delete(Paths_1.default.Equipment.Delete, EquipmentRoutes_1.default.delete);
equipmentRouter.get(Paths_1.default.Equipment.GetRequests, EquipmentRoutes_1.default.getRequest);
equipmentRouter.get(Paths_1.default.Equipment.GetWeather, EquipmentRoutes_1.default.getWeather);
apiRouter.use(Paths_1.default.Equipment._, equipmentRouter);
const maintenanceRouter = (0, express_1.Router)();
maintenanceRouter.get(Paths_1.default.Requests.Get, MaintenanceRequestsRoutes_1.default.get);
maintenanceRouter.post(Paths_1.default.Requests.Add, MaintenanceRequestsRoutes_1.default.add);
maintenanceRouter.get(Paths_1.default.Requests.GetId, MaintenanceRequestsRoutes_1.default.getById);
maintenanceRouter.patch(Paths_1.default.Requests.Patch, MaintenanceRequestsRoutes_1.default.patch);
maintenanceRouter.patch(Paths_1.default.Requests.PatchStatus, MaintenanceRequestsRoutes_1.default.patchStatus);
maintenanceRouter.delete(Paths_1.default.Requests.Delete, MaintenanceRequestsRoutes_1.default.delete);
apiRouter.use(Paths_1.default.Requests._, maintenanceRouter);
exports.default = apiRouter;
